### ISSUE TITLE
How to allign the coordinates between Differential GPS and LiDAR Slam 

### ISSUE THREAD

**Issue by weisongwen** [briannemsick/radmap_preprocess#1]
Dear @briannemsick 

Thanks for your work on this package, I am curious about how do you allign the coordinates between DGPS and LiDAR SLAM (Cartographer)? 
Best 
Welson

**Comment by briannemsick** [comment]
Hi @weisongwen,

I no longer work on this project. However, to the best of my knowledge GPS was added as fixed frame in cartographer. See https://github.com/googlecartographer/cartographer/pull/471.

Best of luck.

**Comment by weisongwen** [comment]
Dear @briannemsick 

Thanks for your kind reply, I will check it later on, 
By the way, do you still conduct research on localization?

Best 
Welson

**Comment by briannemsick** [comment]
Not at this time.

-b
